# Generated by Django 2.2 on 2020-12-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweets',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='tweets',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
